name: fmriprep_docs
channels:
  - conda-forge
dependencies:
- python==3.5
- numpy>=1.11.0
- scipy=0.18.1
- scikit-learn=0.18.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.1
- sphinx_rtd_theme
- future
- nibabel
- statsmodels
- xvfbwrapper
- funcsigs
- networkx>=2.0.0
- python-dateutil
- pydot>=1.2.3
- cython
- nipype>=1.1.6

- pip:
    - sphinx-argparse
    - doctest-ignore-unicode
    - svgutils
    - nitime
    - nilearn
    - niworkflows>=0.7.2,<0.8.0a0
    - smriprep>=0.0.4,<0.1.0a0
    - tedana>=0.0.5
