name: Tests ported from Travis

on: [push]

jobs:
  build-linux:
    if: "!startsWith(github.ref, 'refs/tags/') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8]
        pip: ["pip 'setuptools ~= 42.0' 'setuptools_scm[toml] >= 3.4'"]

    steps:
    - name: Install NeuroDebian & software packages
      run: |
        bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh);
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git-annex-standalone fsl afni ants
    - uses: actions/cache@v1
      with:
        path: /var/lib/apt
        key: apt-cache-v1
        restore-keys: |
          apt-cache-
    - name: Install FreeSurfer's mri_robust_template
      env:
        MRI_ROBUST_TEMPLATE: sx2n7/providers/osfstorage/5e825301d0e35400ebb481f2
        FS_LICENSE: $HOME/.cache/freesurfer/license.txt
      run: |
        curl https://files.osf.io/v1/resources/$MRI_ROBUST_TEMPLATE?direct > mri_robust_template
        sudo install mri_robust_template /usr/local/bin
        mkdir -p $HOME/.cache/freesurfer/
        echo "b2VzdGViYW5Ac3RhbmZvcmQuZWR1CjMwNzU2CiAqQ1MzYkJ5VXMxdTVNCiBGU2kvUGJsejJxR1V3Cg==" | base64 -d > $FS_LICENSE
    - name: Install DataLad
      run: pip install datalad datalad-osf
    - uses: actions/checkout@v2
    - name: Install minimal dependencies
      run: pip install -r min-requirements.txt
    - uses: actions/cache@v1
      with:
        path: $HOME/.cache/pip
        key: pip-cache-v1
        restore-keys: |
          pip-cache-
    - name: Get TemplateFlow's required objects
      run: |
        python -c "from templateflow import api as tfapi;
            tfapi.get('MNI152NLin2009cAsym', resolution=2, desc='brain', suffix='mask');
            tfapi.get('MNI152NLin2009cAsym', resolution=1, label='brain', suffix='probseg');
            tfapi.get('MNI152NLin2009cAsym', resolution=2, desc='fMRIPrep', suffix='boldref');"
    - uses: actions/cache@v1
      with:
        path: $HOME/.cache/templateflow
        key: tf-cache-v1
        restore-keys: |
          tf-cache-
    - name: Install test data
      working-directory: $HOME/data
      run: |
        # ds001600
        datalad install -r https://github.com/nipreps-data/ds001600.git
        datalad update -r --merge -d ds001600/
        datalad get -r -d ds001600/ ds001600/sub-1/

        # HCP/sub-101006
        datalad install -r https://github.com/nipreps-data/HCP101006.git
        datalad update -r --merge -d HCP101006/
        datalad get -r -d HCP101006

        # ds001771
        datalad install -r https://github.com/nipreps-data/ds001771.git
        datalad update --merge -d ds001771/
        datalad get -r -d ds001771/ ds001771/sub-36/fmap/*
    - uses: actions/cache@v1
      with:
        path: $HOME/data
        key: data-cache-v1
        restore-keys: |
          data-cache-
